import type { CSSProperties } from "react";

export const GRID_LINE = "#DADADA";

export const styles: Record<string, CSSProperties> = {
  page: {
    fontFamily: "Inter, sans-serif",
    background: "#FFFFFF",
    minHeight: "100vh",
    color: "#1A1A1A",
  },
  loadingScreen: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: "#FFFFFF",
  },
  topBar: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    background: "#FFFFFF",
    borderBottom: `1px solid ${GRID_LINE}`,
  },
  topBarInner: { maxWidth: 760, margin: "0 auto" },
  brandRow: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 700,
    fontSize: 12.5,
    letterSpacing: 0.6,
    color: "#8A8A8A",
    textTransform: "uppercase",
    marginBottom: 10,
  },
  cellRow: {
    display: "flex",
    border: `1px solid ${GRID_LINE}`,
    borderRadius: 0,
  },
  summaryCell: {
    flex: 1,
    borderRight: `1px solid ${GRID_LINE}`,
    minWidth: 0,
  },
  summaryLabel: {
    fontSize: 10.5,
    color: "#8A8A8A",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontWeight: 600,
    marginBottom: 3,
  },
  beamTrack: {
    marginTop: 10,
    height: 5,
    background: "#EDEDED",
    position: "relative",
    overflow: "hidden",
  },
  beamFill: { position: "absolute", left: 0, top: 0, bottom: 0, transition: "width 200ms ease" },
  beamOverflow: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    background: "repeating-linear-gradient(45deg, #B5432E, #B5432E 4px, #D97757 4px, #D97757 8px)",
  },
  beamIncomeMark: {
    position: "absolute",
    right: 0,
    top: -2,
    bottom: -2,
    width: 2,
    background: "#1A1A1A",
  },
  netChangeCaption: { marginTop: 8, fontSize: 12, color: "#6B6B6B" },

  main: { maxWidth: 760, margin: "0 auto" },
  introText: { fontSize: 13, color: "#8A8A8A", marginTop: 0, marginBottom: 16, lineHeight: 1.5 },

  gridWrap: {
    border: `1px solid ${GRID_LINE}`,
    borderBottom: "none",
    overflowX: "auto",
    width: "100%",
  },
  gridRow: {
    display: "flex",
    width: "100%",
    background: "none",
    border: "none",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: GRID_LINE,
    padding: 0,
    textAlign: "left",
  },
  colCategory: { overflow: "hidden" },
  categoryName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    display: "block",
    width: "100%",
  },

  colHeaderRow: { background: "#F6F6F6" },
  colHeaderCell: {
    fontSize: 10.5,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#8A8A8A",
  },

  groupRow: { background: "#FAFAFA", cursor: "pointer" },
  groupCell: { fontWeight: 700, fontSize: 12.5, color: "#3A3A3A" },

  dataRow: { background: "#FFFFFF" },

  mono: { fontFamily: "'IBM Plex Mono', monospace", fontWeight: 500 },

  targetCell: { cursor: "pointer", position: "relative" },
  targetCellChanged: { background: "#EDF2FA" },
  targetCellEditing: { background: "#EDF2FA", outline: "2px solid #3A5FA0", outlineOffset: -2 },
  targetCellError: { outline: "2px solid #B5432E" },

  editInput: {
    width: "100%",
    height: 24,
    textAlign: "right",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13.5,
    fontWeight: 600,
    border: "none",
    background: "transparent",
    outline: "none",
    padding: 0,
  },
  resetRowBtn: {
    width: 22,
    height: 22,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "none",
    border: "none",
    color: "#B0AA9C",
  },

  bottomBar: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    background: "#FFFFFF",
    borderTop: `1px solid ${GRID_LINE}`,
    zIndex: 30,
    boxShadow: "0 -4px 14px rgba(0,0,0,0.06)",
  },
  bottomBarInner: {
    maxWidth: 760,
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  bottomBarText: { fontSize: 13, color: "#1A1A1A" },
  discardBtn: {
    background: "#FFFFFF",
    border: `1px solid ${GRID_LINE}`,
    color: "#3A3A3A",
    padding: "8px 16px",
    borderRadius: 3,
    fontSize: 13,
    fontWeight: 500,
  },
  applyBtn: {
    background: "#3A5FA0",
    border: "none",
    color: "white",
    padding: "8px 18px",
    borderRadius: 3,
    fontSize: 13,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  toast: {
    position: "fixed",
    bottom: 84,
    left: "50%",
    transform: "translateX(-50%)",
    background: "white",
    border: `1px solid ${GRID_LINE}`,
    borderRadius: 4,
    padding: "9px 16px",
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 500,
    boxShadow: "0 6px 18px rgba(0,0,0,0.10)",
    zIndex: 40,
  },
};
