#!/usr/bin/env bun
// Regenerates src/generated/skill-files.ts, a static-import manifest of every file under
// .claude/skills/cliynab/. `bun build --compile` can only embed files it can see statically
// imported somewhere in the module graph, so a compiled cliynab.exe needs this manifest to carry
// the skill folder's contents with it. Running from source doesn't need this file at all -
// src/commands/skill.ts reads .claude/skills/cliynab/ directly off disk in that case, so it's
// always current there without regenerating anything. This script only matters for `bun run
// build`, which runs it automatically (see the "prebuild" script in package.json).
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";

export const SKILL_ROOT = join(import.meta.dir, "..", ".claude", "skills", "cliynab");
export const OUTPUT_PATH = join(import.meta.dir, "..", "src", "generated", "skill-files.ts");

export async function buildManifest(): Promise<string> {
  const entries = await readdir(SKILL_ROOT, { recursive: true, withFileTypes: true });
  const relativePaths = entries
    .filter((entry) => entry.isFile())
    .map((entry) =>
      relative(SKILL_ROOT, join(entry.parentPath, entry.name)).split(sep).join("/")
    )
    .sort();

  const importLines = relativePaths.map(
    (path, i) => `import f${i} from "../../.claude/skills/cliynab/${path}" with { type: "text" };`
  );
  const entryLines = relativePaths.map(
    (path, i) => `  { relativePath: ${JSON.stringify(path)}, content: f${i} },`
  );

  return `// AUTO-GENERATED by scripts/generate-skill-manifest.ts - do not edit by hand.
${importLines.join("\n")}

export interface SkillFile {
  relativePath: string;
  content: string;
}

export const skillFiles: SkillFile[] = [
${entryLines.join("\n")}
];
`;
}

if (import.meta.main) {
  const output = await buildManifest();
  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, output, "utf-8");
  console.log(`Wrote ${OUTPUT_PATH}`);
}
