name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: DeterminateSystems/nix-installer-action@v22

      - run: nix develop --command bun install --frozen-lockfile

      - run: nix develop --command bun run typecheck

      - run: nix develop --command bun run lint

      - run: nix develop --command bun run fmt:check

      - run: nix develop --command bun run test

      - run: nix build .#linux --impure --no-eval-cache --out-link result-linux
        env:
          YNAB_CLIENT_ID: ${{ secrets.YNAB_CLIENT_ID }}

      - run: nix build .#windows --impure --no-eval-cache --out-link result-windows
        env:
          YNAB_CLIENT_ID: ${{ secrets.YNAB_CLIENT_ID }}

      - uses: actions/upload-artifact@v7
        with:
          name: cliynab-linux
          path: result-linux/bin/cliynab

      - uses: actions/upload-artifact@v7
        with:
          name: cliynab-windows
          path: result-windows/bin/cliynab.exe
